"""new fields in user model

Revision ID: 461c10fc6b6b
Revises: cf4a31d27608
Create Date: 2018-06-28 13:14:36.794036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461c10fc6b6b'
down_revision = 'cf4a31d27608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
