"""followers

Revision ID: 764718de9ef0
Revises: 461c10fc6b6b
Create Date: 2018-06-28 21:48:36.976627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764718de9ef0'
down_revision = '461c10fc6b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
